#!/usr/bin/python

from sys import argv,exit
from math import log,exp

if (len(argv) != 4):
    print(argv[0],"minbeta maxbeta maxbits")
    exit()

betamin = float(argv[1])
betamax = float(argv[2])
maxbits = int(argv[3])

pmin = exp(-4*betamax)
pmax = exp(-4*betamin)

class bitfield:
    def __init__(self):
        self.p = 0
        self.bits = []
        self.lsb = 1 #value of least significant bit
    def append(self,border):
        """add another bit such that the value is still below border"""
        self.lsb /= 2.0
        if self.p + self.lsb < border:
            val = 1
            self.p += self.lsb
        else:
            val = 0
        self.bits = [val] + self.bits
    def inc(self):
        self.p += 2**(-len(self.bits))
        for i in range(len(self.bits)):
            if self.bits[i] == 0:
                self.bits[i] = 1
                break
            else:
                self.bits[i] = 0
    def __repr__(self):
        s = ''
        for i in self.bits:
            if s=='' and i==0:
                continue
            s = str(i)+s
        return "{:6f} {}".format(-0.25*log(self.p), s)

b = bitfield()
inc = 1
for i in range(maxbits):
    b.append(pmin)

b.inc()
while b.p < pmax:
    print(b)
    b.inc()
