[package]
name = "ising"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap = "0.7.0"
signal-hook = "0.3.17"

[dependencies.rand]
version = "0.8.5"
default-features = false
features = ["small_rng", "getrandom"]

[profile.release]
opt-level = 3
strip = true
