#!/usr/bin/python

from sys import argv
from math import log

bits = argv[1]

value = 0
for bit in reversed(bits):
    if bit == '1':
        value += 1
    value /= 2
print("// p = {}".format(value))
print("const double beta = {};".format(-0.25*log(value)))

print("inline Random::result_type Random::e4beta() {")
print("    auto result = r();")

init = False
for bit in reversed(bits):
    if not init:
        if bit == '1':
            init = True
        continue
    print("    result {}= r();".format('|' if bit=='0' else '&'))

print("    return result;")
print("}")
