#!/bin/bash
if [ $# -lt 1 ]; then
    echo "Missing filename."
    exit
fi

function plot {
    ( 
    echo "set yr [0:1]"
    echo "plot '$1' binary format='%float' using :1 w l t ''"
    ) > timeline.gpi 
    gplpdf timeline.gpi > /dev/null
    size=$(cat $1 | wc -c)
    let size/=4
    let size--
    echo $(date +%T) $size
    rm timeline.gpi
}
test -s $1 && plot $1
zathura timeline.pdf &
while true; do
    while [[ ( $1 -ot timeline.pdf ) || ! -s $1 ]]; do
        sleep 1 || exit
    done
    plot $1
done
