#!/usr/bin/env python3

from os import listdir
from subprocess import Popen, PIPE, DEVNULL

for L in sorted(listdir('result')):
    data = []
    chi = 0
    beta = 0
    for f in sorted(listdir('result/'+L)):
        line = open('result/{}/{}'.format(L,f)).read().split()
        if len(line) < 10:
            continue
        d = [float(line[i]) for i in [3,8]]
        if chi < d[1]:
            chi = d[1]
            beta = d[0]
        data.append(d)
    l = 0
    r = 0
    for d in data:
        if l == 0 and d[1] > chi/2:
            l = d[0]
        if d[1] > chi/2:
            r = d[0]
#     print(l,r,beta,chi)
    gnuplot = Popen("gnuplot", stdin=PIPE, stdout=PIPE, stderr=PIPE, universal_newlines=True)
    (out,err) = gnuplot.communicate("""
            l = {l}
            r = {r}
            f(x) = c - a*(x-x0)**2
            x0 = {beta}
            c = {chi}
            a = 2*c/(r-l)**2
            fit [l:r] f(x) "< cat result/{L}/*" using 4:9:10 via a,c,x0
            print x0,x0_err,c,c_err
    """.format(beta=beta, chi=chi, L=L, l=l, r=r))
    print(L,err.split(sep='\n')[-2])

