#!/bin/bash
pow=-1.75
function plot {
(
cat <<'EOF'
set samples 10000
set pointsize 0.3
set bar 0.5
betac = 0.5*atanh(1/sqrt(2))
set key at graph 0.98,0.75 r
set grid
f(x) = -0.25*log(1-x)
g(x) = 1-exp(-4*x)
# set xr [0:0.99]
# set xr [0.69:0.91]
set xr [0.75:0.85]
set link x2 via f(x) inverse g(x)
set xtics nomirror 
set x2tics
set label '$\beta$' at graph 0.99,0.97 r
set label '$1-\mathrm{e}^{-4\beta}$' at graph 0.99,0.09 r
set arrow from g(betac),0 to g(betac),graph 1 nohead dashtype (5,10) lc 0
EOF
if [[ $1 == mag ]]; then
    echo "set yr [0:1]"
    echo "set label '\$M\$' at graph 0.01,0.96 l"
elif [[ $1 == chi ]]; then
    echo "set yr [0:0.06]"
    echo "set label '\$L^{$pow}\\chi\$' at graph 0.005,0.94 l"
fi
echo "p 0 t ''"
lc=1
lt=1
for i in $(ls -v result)
do
    [[ "$(ls result/$i | wc -l )" -gt 2 ]] || continue
    if [[ $1 == mag ]]; then
        echo "rep '< cat result/$i/*' u 3:7:8 w e t '$i' lc $lc lt $lt"
    elif [[ $1 == chi ]]; then
        echo "rep '< cat result/$i/*' u 3:(\$9*\$2**$pow):(\$10*\$2**$pow) w e t '$i' lc $lc lt $lt"
#         echo "rep '' u 3:(\$9*\$2**$pow) smooth cspline t '' lc $lc lt $lt dashtype (5,5)"
    fi
    let lc++
    [[ $lc == 5 ]] && let lc++
    let lt++
done
echo "###MAKEPDF font ',8'"
) > tmp-$1.gpi
gplpdf tmp-$1.gpi > /dev/null
rm tmp-$1.gpi
mv tmp-$1.pdf plot/$1.pdf
}

plot mag &
plot chi
