#!/bin/bash
if [ $# -lt 5 ]; then
    echo "usage: $0 L pmin pmax bits Nmeas"
    exit
fi
L=$1
pmin=$2
pmax=$3
bits=$4
nmeas=$5

sigs=$(sc/bitrange $pmin $pmax $bits)
exe=$pmin-$pmax-$bits
scons -j24 bin/ising exe=$exe sigs="$sigs" L=$L || exit

for sig in $sigs
do
    echo "bin/ising/$L/$exe $sig $nmeas"
done | parallelize 3
